#!/command/with-contenv bash
#shellcheck shell=bash

exec s6wrap --quiet --timestamps --prepend=telegraf --args telegraf \
    --config-directory /etc/telegraf/telegraf.d \
     > >(grep --line-buffered -v -F -e "Error in plugin" -e "error converting to float")
